### ISSUE TITLE
CCLoader freezes CrossCode on startup

### ISSUE THREAD

**Issue by rowanG077** [CCDirectLink/CCLoader#11] opened 2018-08-03 12:43 UTC
I have installed the loader into my main crosscode directory. When I start CrossCode I new get addtional messages like initializing game. 

However when the radicalfishgames logo appears the game freezes. Nothing happens. I have waited more then 10 minutes and it doesn't unfreeze. I actually have to kill the game.

I use ubuntu 18.04.

**Comment by 2767mr** [comment] 2018-08-03 12:44
Is there a white text in the bottom half of you screen?
If yes, please tell me which.

**Comment by rowanG077** [comment] 2018-08-03 12:46
Yes. Initializing mods

**Comment by 2767mr** [comment] 2018-08-03 13:17
I just tested this on Ubuntu 14.04.1 LTS with the newest version of CrossCode and CCLoader and it works without a problem. Your issue might be caused by a mod that fails to load. Please make sure you have updated everything and removed any mods except "simplify" and "OpenDevTools". If the problem still persists, please let me know.

**Comment by rowanG077** [comment] 2018-08-05 17:29
I have found the issue. I am using the i3 window manager and when I move the CrossCode window from one screen to the other screen the game unfreezes and I get a chrome dev tools window on the original screen which prints out "INIT FULLSCREEN VALUE true"

**Comment by 2767mr** [comment] 2018-08-06 14:55
That would be the "OpenDevTools" mod and it is supposed to write this message. There is nothing I can do to fix the freezing. Closing.

**Closed by 2767mr** 2018-08-06 14:55 UTC
